package vista;

import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author desaextremo
 */
public class ActualizarProducto extends javax.swing.JDialog {

    /**
     * Referencia al Frame principal
     */
    private Frame ventana;

    /**
     * Para validar el dialogo se cerro desde el botón X
     */
    private boolean cerroVentana = false;

    /**
     * Creates new form ActualizarProducto
     */
    public ActualizarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.ventana = parent;
        this.cerroVentana = false;
        initComponents();
    }

    /**
     * Accesor para el atributo cajaCodigo
     *
     * @return referencia al atributo cajaCodigo
     */
    public JTextField getCajaCodigo() {
        return cajaCodigo;
    }

    /**
     * Modificador para el atributo cajaCodigo
     *
     * @param cajaCodigo valor parametrico para asignar al atributo 'cajaCodigo'
     */
    public void setCajaCodigo(JTextField cajaCodigo) {
        this.cajaCodigo = cajaCodigo;
    }

    /**
     * Accesor para el atributo cajaNombre
     *
     * @return referencia al atributo cajaNombre
     */
    public JTextField getCajaNombre() {
        return cajaNombre;
    }

    /**
     * Modificador para el atributo cajaNombre
     *
     * @param cajaNombre valor parametrico para asignar al atributo 'cajaNombre'
     */
    public void setCajaNombre(JTextField cajaNombre) {
        this.cajaNombre = cajaNombre;
    }

    /**
     * Accesor para el atributo cajaPrecio
     *
     * @return referencia al atributo cajaPrecio
     */
    public JTextField getCajaPrecio() {
        return cajaPrecio;
    }

    /**
     * Modificador para el atributo cajaPrecio
     *
     * @param cajaPrecio valor parametrico para asignar al atributo 'cajaPrecio'
     */
    public void setCajaPrecio(JTextField cajaPrecio) {
        this.cajaPrecio = cajaPrecio;
    }

    /**
     * Accesor para el atributo cajaInventario
     *
     * @return referencia al atributo cajaInventario
     */
    public JTextField getCajaInventario() {
        return cajaInventario;
    }

    /**
     * Modificador para el atributo cajaInventario
     *
     * @param cajaInventario valor parametrico para asignar al atributo
     * 'cajaInventario'
     */
    public void setCajaInventario(JTextField cajaInventario) {
        this.cajaInventario = cajaInventario;
    }

    /**
     * Accesor para el atributo botonActualizar
     *
     * @return botonActualizar al atributo botonActualizar
     */
    public JButton getBotonActualizar() {
        return botonActualizar;
    }

    /**
     * Modificador para el atributo botonActualizar
     *
     * @param botonActualizar valor parametrico para asignar al atributo
     * 'botonActualizar'
     */
    public void setBotonActualizar(JButton botonActualizar) {
        this.botonActualizar = botonActualizar;
    }

    /**
     * Accesor para el atributo cerroVentana
     *
     * @return cerroVentana al atributo cerroVentana
     */
    public boolean getCerroVentana() {
        return this.cerroVentana;
    }

    /**
     * Modificador para el atributo cerroVentana
     *
     * @param cerroVentana valor parametrico para asignar al atributo
     * 'cerroVentana'
     */
    public void setCerroVentana(boolean cerroVentana) {
        this.cerroVentana = cerroVentana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatos = new javax.swing.JPanel();
        botonActualizar = new javax.swing.JButton();
        etiquetaCodigo = new javax.swing.JLabel();
        cajaCodigo = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        etiquetaPrecio = new javax.swing.JLabel();
        cajaPrecio = new javax.swing.JTextField();
        etiquetaInventario = new javax.swing.JLabel();
        cajaInventario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Producto");

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese Los nuevos Valores"));

        botonActualizar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        botonActualizar.setText("Actualizar Producto");

        etiquetaCodigo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        etiquetaCodigo.setText("Código :");

        cajaCodigo.setEnabled(false);

        etiquetaNombre.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        etiquetaNombre.setText("Nombre : ");

        etiquetaPrecio.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        etiquetaPrecio.setText("Precio : ");

        etiquetaInventario.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        etiquetaInventario.setText("Inventario : ");
        etiquetaInventario.setToolTipText("");

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaCodigo)
                            .addComponent(etiquetaNombre)
                            .addComponent(etiquetaPrecio)
                            .addComponent(etiquetaInventario))
                        .addGap(49, 49, 49)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaCodigo)
                            .addComponent(cajaNombre)
                            .addComponent(cajaPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(cajaInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(botonActualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCodigo)
                    .addComponent(cajaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPrecio)
                    .addComponent(cajaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaInventario)
                    .addComponent(cajaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(botonActualizar)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JTextField cajaCodigo;
    private javax.swing.JTextField cajaInventario;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaPrecio;
    private javax.swing.JLabel etiquetaCodigo;
    private javax.swing.JLabel etiquetaInventario;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaPrecio;
    private javax.swing.JPanel panelDatos;
    // End of variables declaration//GEN-END:variables

}
